export const ActionTypes = {
  CREATE_NEW_PRODUCT: "CREATE_NEW_PRODUCT",
  CREATE_CODE: "CREATE_CODE",
  GET_LIST_PRODUCT : "GET_LIST_PRODUCT",
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  REMOVE_SELECTED: "REMOVE_SELECTED",
  UPDATE_PRODUCT: "UPDATE_PRODUCT"
};
